### ISSUE TITLE
missing calib_velo_to_cam.txt and calib_cam_to_cam.txt

### ISSUE THREAD

**Issue by baidut** [windowsub0406/KITTI_Tutorial#2]
Could you please provide the calibration file?
Thank you!

**Comment by keishatsai** [comment]
Hello,
These file can be found inside the dataset folder. 
/2011_09_26/calib_velo_to_cam.txt

**Comment by baidut** [comment]
Thank you, I found it!

**Comment by robinvista** [comment]
no, there is no such file now
